// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8LFn1gjoxrNMJV5OVvgoKRdktZwKaZo',
    appId: '1:573866015021:web:e812fdf1a7faba59047ba4',
    messagingSenderId: '573866015021',
    projectId: 'quickfoodieapp-f38f4',
    authDomain: 'quickfoodieapp-f38f4.firebaseapp.com',
    storageBucket: 'quickfoodieapp-f38f4.appspot.com',
    measurementId: 'G-7VFKHYK5GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcWNZ3actyUBPqW_RzT0HrYZ97lTsRVic',
    appId: '1:573866015021:android:de3af5330a83bc9a047ba4',
    messagingSenderId: '573866015021',
    projectId: 'quickfoodieapp-f38f4',
    storageBucket: 'quickfoodieapp-f38f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-KIVXauab__M4DLi9WLaCBHar5KjwUqE',
    appId: '1:573866015021:ios:f14a1e11d7386444047ba4',
    messagingSenderId: '573866015021',
    projectId: 'quickfoodieapp-f38f4',
    storageBucket: 'quickfoodieapp-f38f4.appspot.com',
    iosBundleId: 'com.example.deliciousFood',
  );
}
